name: Entrenar y Exportar Modelo DecissionTree

on:
  push:
    branches:
      - recuperativa

jobs:
  train:
    runs-on: self-hosted
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Train Model
        run: |
          python train.py

      - name: Subir Imagenes
        uses: actions/upload-artifact@v3
        with:
          name: Imagenes
          path: ./out/IMAGES/*.png

      - name: Subir Modelo
        uses: actions/upload-artifact@v3
        with:
          name: Modelo-Keras
          path: ./out/MACHINE_MODEL/model.gz
