name: Entrenar y Exportar Modelo LSTM

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Train LSTM Model
        run: |
          python train.py

      - name: Subir Imagenes
        uses: actions/upload-artifact@v3
        with:
          name: Imagenes
          path: ./out/IMAGES/*.png

      - name: Subir Modelo Keras
        uses: actions/upload-artifact@v3
        with:
          name: Modelo-Keras
          path: ./out/HIGH_LEVEL_MODEL/model.keras

      - name: Subir Modelo TfLite
        uses: actions/upload-artifact@v3
        with:
          name: Modelo-TfLite
          path: ./out/LITE_MODEL/model.tflite

      - name: Subir Scaler
        uses: actions/upload-artifact@v3
        with:
          name: Target-Scaler
          path: ./out/SCALER/target-scaler.gz

